<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Phụ thuộc một chiều vào Application -->
    <ProjectReference Include="..\WaterbusSystem.Application\WaterbusSystem.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- EF Core 8 Provider cho SQL Server -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <!-- Quản lý người dùng & phân quyền Identity -->
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />

    <!-- Redis Cache & Khóa phân tán chống Overselling (SET NX PX + Lua safe-release qua StackExchange.Redis) -->
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />

    <!-- Cấu hình Options pattern -->
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

</Project>
